import Link from "next/link";
import { ArrowDown, ArrowUpRight, ChevronRight, Code2, Mail, MapPin } from "lucide-react";
import { portfolio, projects, skillGroups, experiences, education } from "@/data/portfolio";
import { Architecture } from "@/components/portfolio/architecture";
import { ITLab } from "@/components/portfolio/lab";
import { ContactForm } from "@/components/portfolio/contact-form";

function SectionHeading({number,eyebrow,title,children}:{number:string;eyebrow:string;title:string;children?:React.ReactNode}){
  return <div className="section-heading"><div><p className="eyebrow"><span>{number}</span>{eyebrow}</p><h2>{title}</h2></div>{children&&<div className="section-intro">{children}</div>}</div>;
}
export default function Home(){return <main id="main-content">
  <section id="home" className="hero container">
    <div className="hero-copy"><p className="eyebrow"><MapPin aria-hidden="true"/>{portfolio.location}</p><h1><span>Hi, I’m</span>Devanshu<br/>Jamwal<span className="name-period">.</span></h1><p className="hero-specialties">{portfolio.headline}</p><p className="hero-intro">{portfolio.intro}</p><div className="hero-actions"><a className="button button-primary" href="#projects">Explore my work <ArrowDown aria-hidden="true"/></a></div><div className="hero-socials"><a className="text-link" href={portfolio.github} target="_blank" rel="noreferrer"><Code2 aria-hidden="true"/>GitHub <ArrowUpRight aria-hidden="true"/></a>{portfolio.linkedin&&<a className="text-link" href={portfolio.linkedin} target="_blank" rel="noreferrer"><span className="linkedin-icon" aria-hidden="true">in</span>LinkedIn <ArrowUpRight aria-hidden="true"/></a>}</div></div>
    <aside className="hero-profile" aria-label="Professional profile"><div className="profile-index"><span>PROFILE</span><span>DJ / IT</span></div><h2>People.<br/>Systems.<br/><span>Problem solving.</span></h2><div className="profile-rule"/><div className="terminal-intro"><p><span>devanshu@portfolio:~$</span> whoami</p><ul><li>IT Services Graduate</li><li>Calgary, Alberta</li><li>Systems / Networking / Cloud</li><li>Open to IT Opportunities</li></ul></div><p className="profile-foot">SAIT · Information Technology Services</p></aside>
  </section>

  <section id="projects" className="section section-projects"><div className="container"><SectionHeading number="01" eyebrow="Selected work" title="Technical case studies"><p>Academic projects and hands-on labs presented as technical case studies with architecture, implementation notes, troubleshooting, and lessons learned.</p></SectionHeading><div className="project-grid">{projects.map(project=><article className="project-card" key={project.slug}><Link href={`/projects/${project.slug}/`} className="project-visual-link" aria-label={`View ${project.title} case study`}><div className="project-diagram-head"><span>{project.category}</span><span>{project.number}</span></div><Architecture type={project.diagram} compact/></Link><div className="project-card-body"><p className="project-type">{project.type}</p><h3><Link href={`/projects/${project.slug}/`}>{project.title}</Link></h3><p className="project-summary">{project.summary}</p><ul className="inline-terms">{project.featuredTechnologies.map(t=><li key={t}>{t}</li>)}</ul><div className="project-card-bottom"><Link className="text-link" href={`/projects/${project.slug}/`}>View case study <ArrowUpRight aria-hidden="true"/></Link><span>{project.github?"GitHub project":"Hands-on case study"}</span></div></div></article>)}</div></div></section>

  <section id="about" className="section"><div className="container about-layout"><div><p className="eyebrow"><span>02</span>About</p><h2>Technical work.<br/>A human approach.</h2></div><div className="about-copy"><p className="large-copy">I’m an early-career IT professional with hands-on education and technical support experience.</p><p>{portfolio.about}</p><p>I’m looking for an entry-level role where I can contribute, keep learning, and help people work with dependable technology.</p></div></div></section>

  <section id="skills" className="section section-lined"><div className="container"><SectionHeading number="03" eyebrow="Technical skills" title="Across the IT stack"><p>Platforms, tools, and concepts from my education, labs, and support experience.</p></SectionHeading><dl className="skills-list">{skillGroups.map((group,i)=><div key={group.name} className="skill-row"><dt><span>{String(i+1).padStart(2,"0")}</span>{group.name}</dt><dd><ul>{group.skills.map(skill=><li key={skill}>{skill}</li>)}</ul></dd></div>)}</dl></div></section>

  <section id="experience" className="section"><div className="container"><SectionHeading number="04" eyebrow="Experience" title="Supporting users & systems"/><div className="experience-list">{experiences.map(job=><article key={job.company} className="experience-row"><div className="experience-meta"><p>{job.company}</p><span>{job.date}</span><span>{job.location}</span></div><div><h3>{job.role}</h3><ul>{job.points.map(point=><li key={point}>{point}</li>)}</ul></div></article>)}</div></div></section>

  <section id="lab" className="section section-lined"><div className="container"><SectionHeading number="05" eyebrow="Explore the components" title="My IT Lab"><p>Select a component to explore the concepts behind my lab work.</p></SectionHeading><ITLab/></div></section>

  <section id="education" className="section"><div className="container"><SectionHeading number="06" eyebrow="Education" title="The foundation"/><div className="education-layout"><article className="degree"><p className="eyebrow">SAIT · Calgary, Alberta</p><h3>{education.program}</h3><p>{education.school}</p><p className="muted-small">{education.date}</p><ul className="coursework">{education.coursework.map(c=><li key={c}>{c}</li>)}</ul></article><article className="course-training"><h3>Training & technical coursework</h3><p>Coursework and hands-on training; these are not listed as official vendor certifications.</p><ul>{education.training.map(t=><li key={t}><ChevronRight aria-hidden="true"/>{t}</li>)}</ul></article></div></div></section>

  <section id="contact" className="section section-contact"><div className="container contact-layout"><div><p className="eyebrow"><span>07</span>Contact</p><h2>Let’s connect.</h2><p className="contact-copy">I’m currently exploring opportunities in IT support, systems, networking, infrastructure, and related technology roles.</p><ul className="contact-links"><li>{portfolio.email?<a href={`mailto:${portfolio.email}`}><Mail aria-hidden="true"/>{portfolio.email}<ArrowUpRight aria-hidden="true"/></a>:null}</li><li><a href={portfolio.github} target="_blank" rel="noreferrer"><Code2 aria-hidden="true"/>GitHub<ArrowUpRight aria-hidden="true"/></a></li><li>{portfolio.linkedin?<a href={portfolio.linkedin} target="_blank" rel="noreferrer"><span className="linkedin-icon" aria-hidden="true">in</span>LinkedIn<ArrowUpRight aria-hidden="true"/></a>:null}</li></ul></div><ContactForm/></div></section>
</main>}
